---
- name: Setting up nginx and passenger
  become: true
  hosts: all
  gather_facts: False

  vars:
   - MyMessage: "Hello world"

  pre_tasks:
  - name: install python 2
    raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)

  tasks:
    - name: apt - add support for https
      apt:  
        state: present 
        update_cache: yes 
        cache_valid_time: 3600
        pkg:
          - apt-transport-https
          - ca-certificates
          - dirmngr
          - gnupg
          - python-pip

    - name: Nginx setup
      apt: 
        pkg: nginx 
        state: present 
        update_cache: true

    - name: apt - add key for passenger repos
      apt_key: 
        keyserver: keyserver.ubuntu.com
        id: 561F9B9CAC40B2F7
        state: present

    - apt_repository:
        repo: deb https://oss-binaries.phusionpassenger.com/apt/passenger stretch main
        state: present
        filename: passenger
        update_cache: yes

    - name: Install passenger package
      apt:
        name: libnginx-mod-http-passenger
        pkg: libnginx-mod-http-passenger
        state: latest
        update_cache: yes

    - name: Install passenger nginx conf
      raw: if [ ! -f /etc/nginx/modules-enabled/50-mod-http-passenger.conf ]; then sudo ln -s /usr/share/nginx/modules-available/mod-http-passenger.load /etc/nginx/modules-enabled/50-mod-http-passenger.conf ; fi

    - name: Restart service nginx, in all cases
      service:
        name: nginx
        state: restarted

    - name: Copy python application
      copy:
        src: ../webserver/
        dest: /var/www/webserver/
        owner: apollo
        group: apollo
    
    - name: Install python requirements
      raw: pip install -r /var/www/webserver/requirements.txt

    - name: Copy nginx config
      copy:
        src: ./app.conf
        dest: /etc/nginx/sites-enabled/
        owner: apollo
        group: apollo   

    - name: Restart service nginx, in all cases
      service:
        name: nginx
        state: restarted
      
    # - name: index.html copy
      #   template: src=index.html.j2 dest=/usr/share/nginx/html/index.html
# ansible-playbook nginx_install.yaml -i hosts.yaml -u apollo 
